"""
Reporter
========
Responsible for consolidating the results of the mutation-testing pipeline
and producing two artefacts:

1. ``result_calculate`` — a Python dict (serialisable to JSON) containing
   the mutation score, status counts and per-mutant diffs.
2. ``report.html``      — a self-contained HTML page written to the same
   directory as the original PySpark program.

Methods must be called in order (as MutationManager does)::

    reporter = Reporter(result_list, code_original, mutant_list)
    reporter.calculate()       # compute score + group by status
    reporter.make_diff()       # compute diffs and add to result_calculate
    reporter.show_results()    # write report.html to disk

Deliberately out of scope
--------------------------
- Running tests               → TestRunner
- Orchestrating the pipeline  → MutationManager
"""

import difflib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from .test_result import TestResult

if TYPE_CHECKING:
    from .operator import Mutant


@dataclass
class Reporter:
    """
    Aggregates mutation-testing results and produces reports.

    Parameters
    ----------
    result_list   : list[TestResult]
        One ``TestResult`` per mutant, returned by ``TestRunner.run_test()``.
    code_original : str
        Raw source code of the original PySpark application.
    mutant_list   : list[Mutant]
        All mutants generated by the operators.
    result_calculate : dict
        Populated by ``calculate()`` and enriched by ``make_diff()``.
        Serialisable to JSON.  Empty on construction.
    """

    result_list:      list[TestResult]
    code_original:    str
    mutant_list:      list
    result_calculate: dict = field(default_factory=dict)

    # ------------------------------------------------------------------ #
    # Post-init validation                                                 #
    # ------------------------------------------------------------------ #

    def __post_init__(self) -> None:
        self._validate_result_list()
        self._validate_code_original()
        self._validate_mutant_list()

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    def calculate(self) -> "Reporter":
        """
        Compute the mutation score and group results by status.

        The mutation score is defined as::

            killed / (killed + survived + timeout + error)

        All counts and the score are written to ``result_calculate``.

        Returns
        -------
        self — for method chaining.
        """
        total    = len(self.result_list)
        killed   = sum(1 for r in self.result_list if r.status == "killed")
        survived = sum(1 for r in self.result_list if r.status == "survived")
        timeout  = sum(1 for r in self.result_list if r.status == "timeout")
        error    = sum(1 for r in self.result_list if r.status == "error")

        score = round(killed / total, 4) if total > 0 else 0.0

        self.result_calculate.update({
            "mutation_score": score,
            "total":          total,
            "killed":         killed,
            "survived":       survived,
            "timeout":        timeout,
            "error":          error,
            "diff_original_code": [],   # populated by make_diff()
        })

        print(
            f"[Reporter.calculate] Score={score:.2%} | "
            f"killed={killed} survived={survived} "
            f"timeout={timeout} error={error} total={total}"
        )
        return self

    def make_diff(self) -> "Reporter":
        """
        Compute a unified diff between the original source and each mutant,
        and append the results to ``result_calculate['diff_original_code']``.

        Each entry in the list follows the format::

            { "<operator_name>_<mutant_id>": "<unified diff string>" }

        Returns
        -------
        self — for method chaining.

        Raises
        ------
        RuntimeError
            If ``calculate()`` has not been called yet.
        """
        self._assert_calculated()

        # Build a lookup from mutant id → Mutant for O(1) access
        mutant_index = {m.id: m for m in self.mutant_list}

        diffs: list[dict] = []

        for result in self.result_list:
            mutant = mutant_index.get(result.mutant)
            if mutant is None:
                continue

            try:
                mutant_source = Path(mutant.mutant_path).read_text(
                    encoding="utf-8"
                )
            except (FileNotFoundError, OSError) as exc:
                print(
                    f"[Reporter.make_diff] Could not read mutant file "
                    f"'{mutant.mutant_path}': {exc} — skipping."
                )
                continue

            diff_lines = difflib.unified_diff(
                self.code_original.splitlines(keepends=True),
                mutant_source.splitlines(keepends=True),
                fromfile="original",
                tofile=f"{mutant.operator.lower()}_{mutant.id}",
                lineterm="",
            )
            diff_str = "".join(diff_lines)

            key = f"{mutant.operator.lower()}_{mutant.id}"
            diffs.append({key: diff_str})

        self.result_calculate["diff_original_code"] = diffs

        print(f"[Reporter.make_diff] {len(diffs)} diff(s) generated.")
        return self

    def show_results(self) -> "Reporter":
        """
        Write a self-contained HTML report to disk.

        The file is saved as ``report.html`` in the same directory as the
        original PySpark program (derived from the first mutant's
        ``original_path``).  If no mutants exist, the file is written to
        the current working directory.

        Returns
        -------
        self — for method chaining.

        Raises
        ------
        RuntimeError
            If ``calculate()`` has not been called yet.
        """
        self._assert_calculated()

        output_dir  = self._resolve_output_dir()
        output_path = output_dir / "report.html"

        html = self._build_html()
        output_path.write_text(html, encoding="utf-8")

        print(f"[Reporter.show_results] Report saved to: {output_path}")
        return self

    # ------------------------------------------------------------------ #
    # Private helpers                                                      #
    # ------------------------------------------------------------------ #

    def _resolve_output_dir(self) -> Path:
        """Return the directory where report.html should be written."""
        if self.mutant_list:
            return Path(self.mutant_list[0].original_path).parent
        return Path.cwd()

    def _build_html(self) -> str:
        """Build and return the full HTML report as a string."""
        rc    = self.result_calculate
        score = rc.get("mutation_score", 0.0)
        score_pct   = f"{score * 100:.1f}%"
        score_class = (
            "score-high"   if score >= 0.80 else
            "score-medium" if score >= 0.50 else
            "score-low"
        )

        # ── Summary cards ──────────────────────────────────────────────
        summary_cards = "".join([
            self._card("Mutation score", score_pct,   score_class),
            self._card("Total",          rc.get("total",    0), ""),
            self._card("Killed",         rc.get("killed",   0), "card-killed"),
            self._card("Survived",       rc.get("survived", 0), "card-survived"),
            self._card("Timeout",        rc.get("timeout",  0), "card-timeout"),
            self._card("Error",          rc.get("error",    0), "card-error"),
        ])

        # ── Results table rows ─────────────────────────────────────────
        mutant_index = {m.id: m for m in self.mutant_list}
        table_rows   = ""
        for result in self.result_list:
            mutant       = mutant_index.get(result.mutant)
            operator     = mutant.operator if mutant else "—"
            modified     = mutant.modified_line if mutant else "—"
            status_class = f"status-{result.status}"
            failed       = (
                "<br>".join(result.failed_tests)
                if result.failed_tests else "—"
            )
            table_rows += (
                f"<tr>"
                f"<td>{result.mutant}</td>"
                f"<td>{operator}</td>"
                f"<td><code>{self._escape(modified)}</code></td>"
                f"<td class='{status_class}'>{result.status.upper()}</td>"
                f"<td>{failed}</td>"
                f"<td>{result.execution_time:.4f}s</td>"
                f"</tr>\n"
            )

        # ── Diff section ───────────────────────────────────────────────
        diff_blocks = ""
        for entry in rc.get("diff_original_code", []):
            for key, diff_str in entry.items():
                diff_html    = self._escape(diff_str)
                colored_diff = self._colorise_diff(diff_html)
                diff_blocks += (
                    f"<details>"
                    f"<summary><strong>{key}</strong></summary>"
                    f"<pre class='diff'>{colored_diff}</pre>"
                    f"</details>\n"
                )

        # ── JSON dump ──────────────────────────────────────────────────
        json_dump = self._escape(
            json.dumps(
                {k: v for k, v in rc.items() if k != "diff_original_code"},
                indent=2,
            )
        )

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mutation Testing Report</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; }}
    body {{ font-family: system-ui, sans-serif; margin: 0; padding: 24px;
           background: #f5f5f5; color: #1a1a1a; }}
    h1 {{ margin: 0 0 24px; font-size: 1.6rem; }}
    h2 {{ font-size: 1.1rem; margin: 32px 0 12px; color: #444; }}

    /* ── Summary cards ── */
    .cards {{ display: flex; flex-wrap: wrap; gap: 16px; margin-bottom: 32px; }}
    .card  {{ background: #fff; border-radius: 10px; padding: 20px 28px;
              min-width: 140px; box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
    .card .label {{ font-size: .8rem; color: #666; margin-bottom: 4px; }}
    .card .value {{ font-size: 2rem; font-weight: 700; }}
    .score-high   .value {{ color: #16a34a; }}
    .score-medium .value {{ color: #d97706; }}
    .score-low    .value {{ color: #dc2626; }}
    .card-killed   .value {{ color: #16a34a; }}
    .card-survived .value {{ color: #dc2626; }}
    .card-timeout  .value {{ color: #d97706; }}
    .card-error    .value {{ color: #6b7280; }}

    /* ── Table ── */
    .table-wrap {{ overflow-x: auto; }}
    table {{ width: 100%; border-collapse: collapse; background: #fff;
             border-radius: 10px; overflow: hidden;
             box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
    th {{ background: #f0f0f0; text-align: left; padding: 10px 14px;
          font-size: .8rem; text-transform: uppercase; letter-spacing: .04em; }}
    td {{ padding: 9px 14px; font-size: .9rem;
          border-top: 1px solid #f0f0f0; vertical-align: top; }}
    tr:hover td {{ background: #fafafa; }}
    .status-killed   {{ color: #16a34a; font-weight: 600; }}
    .status-survived {{ color: #dc2626; font-weight: 600; }}
    .status-timeout  {{ color: #d97706; font-weight: 600; }}
    .status-error    {{ color: #6b7280; font-weight: 600; }}
    code {{ background: #f3f4f6; padding: 1px 5px; border-radius: 4px;
            font-size: .85rem; }}

    /* ── Diffs ── */
    details {{ background: #fff; border-radius: 8px; margin-bottom: 8px;
               box-shadow: 0 1px 3px rgba(0,0,0,.07); }}
    summary {{ padding: 12px 16px; cursor: pointer; font-size: .9rem;
               list-style: none; }}
    summary::-webkit-details-marker {{ display: none; }}
    summary::before {{ content: '▶ '; font-size: .7rem; }}
    details[open] summary::before {{ content: '▼ '; }}
    pre.diff {{ margin: 0; padding: 16px; overflow-x: auto;
                font-size: .82rem; line-height: 1.6;
                background: #1e1e1e; color: #d4d4d4;
                border-radius: 0 0 8px 8px; }}
    .diff-add {{ color: #4ec994; }}
    .diff-del {{ color: #f47067; }}
    .diff-hdr {{ color: #858585; }}

    /* ── JSON block ── */
    pre.json {{ background: #1e1e1e; color: #d4d4d4; padding: 20px;
                border-radius: 10px; font-size: .82rem; overflow-x: auto; }}
  </style>
</head>
<body>
  <h1>Mutation Testing Report</h1>

  <div class="cards">{summary_cards}</div>

  <h2>Results per mutant</h2>
  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th>ID</th><th>Operator</th><th>Modified line</th>
          <th>Status</th><th>Failed tests</th><th>Time</th>
        </tr>
      </thead>
      <tbody>
        {table_rows}
      </tbody>
    </table>
  </div>

  <h2>Diffs (original vs mutant)</h2>
  {diff_blocks if diff_blocks else "<p>No diffs available.</p>"}

  <h2>Raw JSON</h2>
  <pre class="json">{json_dump}</pre>

</body>
</html>"""

    # ── HTML helpers ──────────────────────────────────────────────────

    @staticmethod
    def _card(label: str, value, extra_class: str) -> str:
        cls = f"card {extra_class}".strip()
        return (
            f"<div class='{cls}'>"
            f"<div class='label'>{label}</div>"
            f"<div class='value'>{value}</div>"
            f"</div>"
        )

    @staticmethod
    def _escape(text: str) -> str:
        """Escape special HTML characters in a string."""
        return (
            text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace('"', "&quot;")
        )

    @staticmethod
    def _colorise_diff(escaped_diff: str) -> str:
        """
        Wrap added/removed/header lines of a pre-escaped unified diff in
        ``<span>`` elements for syntax colouring.
        """
        lines  = escaped_diff.split("\n")
        result = []
        for line in lines:
            if line.startswith("+") and not line.startswith("+++"):
                result.append(f"<span class='diff-add'>{line}</span>")
            elif line.startswith("-") and not line.startswith("---"):
                result.append(f"<span class='diff-del'>{line}</span>")
            elif line.startswith("@@") or line.startswith("---") or line.startswith("+++"):
                result.append(f"<span class='diff-hdr'>{line}</span>")
            else:
                result.append(line)
        return "\n".join(result)

    # ------------------------------------------------------------------ #
    # Guards                                                               #
    # ------------------------------------------------------------------ #

    def _assert_calculated(self) -> None:
        if "mutation_score" not in self.result_calculate:
            raise RuntimeError(
                "[Reporter] result_calculate is not populated. "
                "Call calculate() before make_diff() or show_results()."
            )

    # ------------------------------------------------------------------ #
    # Validators                                                           #
    # ------------------------------------------------------------------ #

    def _validate_result_list(self) -> None:
        if not isinstance(self.result_list, list):
            raise TypeError(
                f"[Reporter] result_list must be a list, "
                f"got: {type(self.result_list)}"
            )
        invalid = [r for r in self.result_list if not isinstance(r, TestResult)]
        if invalid:
            raise TypeError(
                f"[Reporter] All items in result_list must be TestResult "
                f"instances. Found {len(invalid)} invalid item(s)."
            )

    def _validate_code_original(self) -> None:
        if not isinstance(self.code_original, str) or not self.code_original.strip():
            raise ValueError(
                "[Reporter] code_original must be a non-empty string."
            )

    def _validate_mutant_list(self) -> None:
        if not isinstance(self.mutant_list, list):
            raise TypeError(
                f"[Reporter] mutant_list must be a list, "
                f"got: {type(self.mutant_list)}"
            )

    # ------------------------------------------------------------------ #
    # Dunder helpers                                                       #
    # ------------------------------------------------------------------ #

    def __repr__(self) -> str:
        score = self.result_calculate.get("mutation_score", "not calculated")
        return (
            f"Reporter("
            f"results={len(self.result_list)}, "
            f"mutants={len(self.mutant_list)}, "
            f"score={score}"
            f")"
        )